# Generated by Django 3.2 on 2022-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0022_auto_20221111_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
